Vagrant.configure("2") do |config|
    config.vm.box ="almalinux/9"
    config.vm.synced_folder ".","/vagrant"

    {
        "jenkins" => ["192.168.56.10","scripts/jenkins.sh"],
        "sonarqube" => ["192.168.56.11","scripts/sonarqube.sh"],
        "nexus" => ["192.168.56.12","scripts/nexus.sh"],
    }.each do |name,(ip,script)|
        config.vm.define name do |vm|
            vm.vm.hostname = "#{name}.local"
            vm.vm.network "private_network", ip: ip
            vm.vm.provision "shell", path: script
        end
    end
end

