pipeline {
  agent any

  environment {
    BUCKET_NAME = "my-angular-app-bucket"
  }

  stages {

    stage('Install Dependencies') {
      steps {
        sh 'npm install'
      }
    }

    stage('Build Angular App') {
      steps {
        sh 'npm run build -- --configuration production'
      }
    }

    stage('Terraform Init & Apply') {
      steps {
        dir('terraform') {
          sh '''
            terraform init
            terraform apply -auto-approve \
              -var="bucket_name=${BUCKET_NAME}"
          '''
        }
      }
    }

    stage('Upload to S3') {
      steps {
        sh '''
          aws s3 sync dist/ s3://${BUCKET_NAME} \
            --delete
        '''
      }
    }
  }
}
